//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kusget2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOylar
    {
        public int id { get; set; }
        public string kullananTC { get; set; }
        public string kullananAdi { get; set; }
        public string vekilTC { get; set; }
        public string vekilAdi { get; set; }
        public Nullable<bool> vekalet { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
