//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kusget2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSecmen
    {
        public int id { get; set; }
        public string TCno { get; set; }
        public string adi { get; set; }
    }
}
